name: Publish feed.json

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Build
      env:
        TITLE: Core ML Playground Book
        SUBTITLE: Machine Learning Examples
        PUBLISHER_NAME: Kenta Kubo
        FEED_IDENTIFIER: xyz.kebo.playgroundbook.coreml
        CONTACT_URL: https://kebo.xyz
        DOCUMENT_TITLE: CoreML
        DOCUMENT_OVERVIEW_SUBTITLE: Machine Learning Examples
        DOCUMENT_DESCRIPTION: Machine Learning Examples
        DOCUMENT_CONTENT_IDENTIFIER: xyz.kebo.playgroundbook.coreml.coreml
        DOCUMENT_URL: https://kebo.xyz/coreml-playground/CoreML.playgroundbook.zip
        PLAYGROUNDBOOK_FILENAME: CoreML.playgroundbook
      run: |
        zip -r "${PLAYGROUNDBOOK_FILENAME}.zip" "${PLAYGROUNDBOOK_FILENAME}"
        DOCUMENT_SHA512=$(sha512sum "${PLAYGROUNDBOOK_FILENAME}.zip" | awk '{print $1}')
        DOCUMENT_PUBLISHED_DATE=2019-05-06T02:40:00+0900
        DOCUMENT_LAST_UPDATED_DATE=$(date -Iseconds)
        TAG_NAME=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///g')
        DOCUMENT_CONTENT_VERSION=$(echo $TAG_NAME | cut -c 2-)
        cat > feed.json << EOF
        {
            "title": "${TITLE}",
            "subtitle": "${SUBTITLE}",
            "publisherName": "${PUBLISHER_NAME}",
            "feedIdentifier": "${FEED_IDENTIFIER}",
            "contactURL": "${CONTACT_URL}",
            "formatVersion": "1.2",
            "documents": [
                {
                    "title": "${DOCUMENT_TITLE}",
                    "overviewSubtitle": "${DOCUMENT_OVERVIEW_SUBTITLE}",
                    "description": "${DOCUMENT_DESCRIPTION}",
                    "contentIdentifier": "${DOCUMENT_CONTENT_IDENTIFIER}",
                    "contentVersion": "${DOCUMENT_CONTENT_VERSION}",
                    "url": "${DOCUMENT_URL}",
                    "publishedDate": "${DOCUMENT_PUBLISHED_DATE}",
                    "lastUpdatedDate": "${DOCUMENT_LAST_UPDATED_DATE}",
                    "sha512": "${DOCUMENT_SHA512}",
                    "thumbnailURL": "https://raw.githubusercontent.com/kkk669/coreml-playground/${TAG_NAME}/images/thumbnail.png",
                    "bannerImageURL": "https://raw.githubusercontent.com/kkk669/coreml-playground/${TAG_NAME}/images/banner.png",
                    "previewImageURLs": [
                        "https://raw.githubusercontent.com/kkk669/coreml-playground/${TAG_NAME}/images/preview.png"
                    ],
                    "additionalInformation": [
                        {
                            "name": "Languages",
                            "value": "English"
                        }
                    ]
                }
            ]
        }
        EOF
        mkdir public && mv "${PLAYGROUNDBOOK_FILENAME}.zip" feed.json public/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: public
